feat: Enable mTLS on Ingress and make storageClassName configurable
lenny-intel/edgex-helm pull request #10
Opened 2022-02-02 19:24 UTC by bnevis-i

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

2022-02-03 15:21 UTC, lenny-intel requested changes

2022-02-03 15:21 UTC, lenny-intel commented on README.md
> +Set `enabled` to `true` and specify a custom hostname for use on the ingress
Rather editing the file we should instruct to use `helm install edgex-jakarta --set secuirty.enabled=true -n edgex .` below to run in secure mode. Then this section can be removed.

2022-02-03 15:21 UTC, lenny-intel commented on README.md
> +helm install edgex-jakarta -n edgex .
```suggestion
helm install edgex-jakarta --set secuirty.enabled=true -n edgex .
```

2022-02-03 15:21 UTC, lenny-intel commented on README.md
> +helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
Can this be made part of our helm so `ingress-nginx` doesn't have to be installed separately?

2022-02-03 15:21 UTC, lenny-intel commented on pingtest.sh
> +curl -iv --resolve edgex:443:192.168.122.200 --cacert server-ca.pem --cert client.pem --key client.key "https://edgex/core-data/api/v2/ping"
The IP address will be different per user's system. Script should first determine the IP. I assume it needs to be the actual IP and not `localhost`

2022-02-03 16:50 UTC, bnevis-i commented on README.md
> +Set `enabled` to `true` and specify a custom hostname for use on the ingress
Updated.

2022-02-03 16:50 UTC, bnevis-i commented on README.md
> +helm install edgex-jakarta -n edgex .
Updated.

2022-02-03 16:52 UTC, bnevis-i commented on README.md
> +helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
No, I don't think so.  There are dozens of available ingress controllers, and which one you get by default depends on your Kubernetes vendor.  Replaced with a URL to the Ngnix ingress installation instructions.

2022-02-03 16:53 UTC, bnevis-i commented on pingtest.sh
> +curl -iv --resolve edgex:443:192.168.122.200 --cacert server-ca.pem --cert client.pem --key client.key "https://edgex/core-data/api/v2/ping"
Actually, I missed the MetalLB dependency.  Added that, and documented that this IP is the metalLB IP.  This will of course vary based on the user's environment.  Also, removed the `pingtest.sh` script and put the `curl` command inline into the README.

2022-02-03 16:54 UTC, bnevis-i commented on pingtest.sh
> +curl -iv --resolve edgex:443:192.168.122.200 --cacert server-ca.pem --cert client.pem --key client.key "https://edgex/core-data/api/v2/ping"
Like Ngnix, there are dozens of load balancer options that the user can choose as well, and a half dozen for bare metal load balancing alone.

2022-02-07 16:54 UTC, lenny-intel requested changes

2022-02-07 16:54 UTC, lenny-intel commented on README.md
> +curl -iv --resolve edgex:443:192.168.122.200 --cacert server-ca.pem --cert client.pem --key client.key "https://edgex/core-data/api/v2/ping"
IMO, need to point out here that this IP will differ on each system and that it is the IP of the MetalLB

2022-02-07 21:39 UTC, lenny-intel commented on README.md
> +curl -iv --resolve edgex:443:192.168.122.200 --cacert server-ca.pem --cert client.pem --key client.key "https://edgex/core-data/api/v2/ping"
```suggestion
curl -iv --resolve edgex:443:<MetalLB IP> --cacert server-ca.pem --cert client.pem --key client.key "https://edgex/core-data/api/v2/ping"
```

2022-02-07 21:52 UTC, bnevis-i commented on README.md
> +curl -iv --resolve edgex:443:192.168.122.200 --cacert server-ca.pem --cert client.pem --key client.key "https://edgex/core-data/api/v2/ping"
Fixed.

2022-02-07 23:46 UTC, lenny-intel approved these changes
LGTM

2022-02-07 23:46 UTC, merged